@startuml
start
:Регистрация/авторизация клиента;
if (У пользователя уже есть аккаунт?) then (да)
:Входит в существующий аккаунт;
else (нет)
:Клиент регистрируется на сайте;
endif

:Клиент выбирает товары и добавляет их в корзину;
:Клиент переходит к оформлению заказа, выбирает способ доставки и оплаты;
:Система проверяет наличие каждого товара в выбранных количествах;

if (Все необходимые товары в нужном кол-ве в наличии?) then (да)
else (нет)
:Уведомление клиента о недоступности товара;
:Предоставление возможности выбрать альтернативный товар или удалить отсутствующий из заказа;
endif

fork
:Оплата заказа;
:Клиент выбирает способ оплаты (кредитная карта, PayPal, банковский перевод и т. д.);
:Система проверяет платёжные детали и производит транзакцию;

if (Проблема с оплатой?) then (да)
    :Уведомление клиента о проблеме с платежом;
    if (Причина отказа платежа?) then (Недостаточно средств)
        :Уведомление клиента о недостатке средств;
    else if (Неверные платёжные данные) then
        :Уведомление клиента о неверных платёжных данных;
    else (Платёжная система недоступна)
        :Уведомление клиента о недоступности платёжной системы;
    endif
    :Предложение альтернативных способов оплаты;
    :Возможность связаться со службой поддержки для уточнения деталей;

    if (Клиента устраивает решение?) then (да)
        :Клиент повторяет попытку оплаты;
    else (нет)
        :Заказ отменяется.;
        :Клиенту возвращаются средства (если были списаны);
        stop
    endif

else (нет)
    :Подготовка товара к отправке;
    :Система уведомляет склад о необходимости собрать заказ;
    :Сотрудники склада комплектуют заказ по списку;
end fork

if (Оплата прошла успешно и товар готов к отправке?) then (да)
:Генерируется счёт-фактура;
:Отправляется уведомление клиенту о подтверждении заказа и статусе доставки;
:Заказ переходит в статус «Отправлен»;
else (нет)
:Отправляется уведомление клиенту о проблеме с платежом;
endif

:Система обновляет статус заказа по мере его продвижения к доставке;
:Клиент получает уведомления о каждом изменении статуса (подтверждение, отправка, доставка);

stop
@enduml
